package uz.techie.mahsulot.model

data class Stream(
    val id: Int?,
    val yangi: Int?,
    val qabul_qilindi: Int?,
    val yetkazilmoqda: Int?,
    val yetqazib_berildi: Int?,
    val arxivlandi: Int?,
    val qayta_qungiroq: Int?,
    val nosoz_mahsulot: Int?,
    val spam: Int?,
    val arxivlanmoqda: Int?,
    val muzlatildi: Int?,
    val price: Int?,
    val bonus: Int?,
    val marja: Int?,
    val name: String?,
    val status: String?,
    val url: String?,
    val reklama_link: String?,
    val create_at: String?,
    val update_at: String?,
    val product_id: Int?,
    val seller_id: Int?,
)